server:
  port: 8080
  servlet:
    context-path: /desafio-vertical-logistica/api

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/vertical_logistica?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always